service: auction-service
frameworkVersion: "2"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ap-south-1

functions:
  ping:
    handler: src/handlers/ping.ping
    events:
      - http:
          method: GET
          path: /ping
          cors : true
